### ISSUE TITLE
Feature request: Add replace task to the core tasks.

### ISSUE THREAD

**Issue by ghost** [php-taskman/core-tasks#1]
I have a use case where I want to replace configuration from Drupal during a deploy sequence before importing the configuration.

I need to replace the configuration of readonlymode.settings to be enabled before importing my new configuration. Otherwise the site will be set out of readonlymode again. And it defeats the purpose of setting the config first:

```yaml
commands:
    build:deploy:
        description: Deploy sequence after checkout.
        tasks:
            - ./vendor/bin/drush config:set readonlymode.settings enabled 1 -y
            - { task: "replace", file: "config/sync/readonlymode.settings.yml", from: "enabled: 0", to: "enabled: 1" }
            - ./vendor/bin/drush config:import -y
            - ./vendor/bin/drush updatedb -y
            - { task: "replace", file: "config/sync/readonlymode.settings.yml", from: "enabled: 1", to: "enabled: 0" }
            - ./vendor/bin/drush config:set readonlymode.settings enabled 0 -y
```
But this task seems to be missing from the core tasks. I'll make a pull request providing this task.

**Comment by ghost** [comment]
Hi Pol,

Again I'm missing access rights to this repository. Are you sure you don't want me to work from a fork? For me it's not a problem at all doing it that way...

```
ERROR: Permission to php-taskman/core-tasks.git denied to verbruggenalex.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by drupol** [comment]
Hi Alex,

Permissions needs to be setup per repository, I haven't gave you access to all of them, not because I don't want you to work from it, just because I didn't know that!!
I will fix this right now, working from a fork could be boring.

**Comment by drupol** [comment]
Done, added you on core and core-tasks project.

**Comment by drupol** [comment]
Regarding the issue, have you checked out the '**process**' task ? I think it's doing what you're looking for.

**Comment by ghost** [comment]
Thx! I switched the PR to use BaseTask as class extension. Seems more appropriate.

But I'm starting to doubt my approach on my use case. I think I shouldn't be altering config or settings.php during a deployment. I'm more thinking of having a special settings.deploy.php to include depending on an environment variable. This would allow me to force the readonlymode to be in effect during deployment...

**Comment by drupol** [comment]
Have you checked out the **process** task ?

What do you think ?

**Comment by ghost** [comment]
I've used the process task before. It's useful for when you need to replace multiple variables. But in my case (.env file) I'm not using any replacements. And it feels like overkill to put all my environment variables inside of taskman.yml as a matter of being consistent. Having multiple taskman.yml files instead of multiple .env files (one per environment)...

I'm also not entirely sure I want to use the replace task. But I don't see any better options at the moment. Editing the .env file seems acceptable in case of a deployment.

```yaml
commands:
    build:deploy:
        description: Deploy sequence after checkout.
        tasks:
            - { task: "replace", file: ".env", from: "DRUPAL_DEPLOY_IN_PROGRESS=0", to: "DRUPAL_DEPLOY_IN_PROGRESS=1" }
            - ./vendor/bin/drush cc drush
            - ./vendor/bin/drush cache:rebuild
            - ./vendor/bin/drush config:import -y
            - ./vendor/bin/drush updatedb -y
            - ./vendor/bin/drush core:cron
            - ./vendor/bin/drush cache:rebuild
            - { task: "replace", file: ".env", from: "DRUPAL_DEPLOY_IN_PROGRESS=1", to: "DRUPAL_DEPLOY_IN_PROGRESS=0" }
```

I just thought that the replace task would be a nice addition to the core tasks.
